auto: true

paginate: 8
permalink: /blog/:year/:month/:day/:title.html

title: FindShine
url: http://www.findshine.com/blog/
feed: blog/atom.xml
author_info: <a href="http://www.findshine.com/blog">FanShen</a>
layouts_dir: blog/_layouts